[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "rustywoof"
dynamic = ["version"]
description = "A blazing fast, relentless secret scanner & supply chain defensive tool. Written in Rust"
requires-python = ">=3.8"
license = { text = "MIT OR Apache-2.0" }

[tool.maturin]
bindings = "bin"
