// src/error.rs

use miette::Diagnostic;
use thiserror::Error;

/// Defines all systemic errors encountered by the Rustywoof watchdog.
/// Integrating this ensures a uniform, enterprise-grade diagnostic output.
#[derive(Error, Debug, Diagnostic)]
pub enum SystemError {
    #[error("Perimeter Configuration Failure")]
    #[diagnostic(
        code(woof::config::io_error),
        help("Verify that you have write permissions in the current directory.")
    )]
    ConfigWriteFailed(#[source] std::io::Error),

    #[error("Invalid Configuration Syntax")]
    #[diagnostic(
        code(woof::config::parse_error),
        help("The .woof.toml file contains invalid formatting. Please check your syntax.")
    )]
    ConfigParseFailed(#[source] toml::de::Error),

    #[error("Configuration Serialization Failed")]
        #[diagnostic(
            code(woof::config::serialize_error),
            help("Failed to write the default configuration to string formatting.")
        )]
        ConfigSerializeFailed(#[source] toml::ser::Error),

    #[error("Perimeter Guard Hook Failure")]
    #[diagnostic(
        code(woof::git::hook_error),
        help("Failed to install the pre-commit hook. Ensure this is a valid Git repository.")
    )]
    GitHookFailed(#[source] std::io::Error),
    #[error("Perimeter Audit Failed: No lockfiles detected.")]
    #[diagnostic(
        code(woof::audit::no_lockfiles),
        help(
            "Rustywoof supports npm, pnpm, yarn, cargo, poetry, and pip. Ensure you are running this command in a project root."
        )
    )]
    NoLockfilesFound,

    #[error("Lockfile Corruption Detected: {file_name}")]
    #[diagnostic(
        code(woof::audit::corrupt_lockfile),
        help(
            "Failed to parse the lockfile. Ensure it is well-formed and generated by the official package manager."
        )
    )]
    LockfileParseError {
        file_name: String,
        #[source]
        source: anyhow::Error,
    },
}
